[dashboards]
# Minimum dashboard refresh interval. When this is lower than the refresh interval configured for the dashboard,
# the latter will take precedence.
# The default is 5s, but we're setting it to 100ms to allow for near real-time telemetry updates
min_refresh_interval = 50ms

[dataproxy]
# This setting controls timeout for dataproxy requests to data sources
timeout = 300
# This setting controls timeout for outgoing http requests (to data sources)
send_timeout = 300

[server]
# Enable gzip compression
enable_gzip = true
