{
 "title": "RPM",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "RPM",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"f1-telemetry\")\r\n  |> range(start: -30s)\r\n  |> filter(fn: (r) => r._measurement == \"f1_telemetry\")\r\n  |> filter(fn: (r) => r._field == \"rpm\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Gear",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"f1-telemetry\")\r\n  |> range(start: -30s)\r\n  |> filter(fn: (r) => r._measurement == \"f1_telemetry\")\r\n  |> filter(fn: (r) => r._field == \"gear\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"f1-telemetry\")\r\n  |> range(start: -30s)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"f1_telemetry\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"speed_kmh\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Throttle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"f1-telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"f1_telemetry\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"throttle\")\r\n  |> aggregateWindow(every: 100ms, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: r._value * 100.0 }))\r\n  |> yield(name: \"throttle\")"
    }
   ]
  },
  {
   "title": "Brake",
   "type": "timeseries",
   "description": "Brake",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"f1-telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"f1_telemetry\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"brake\")\r\n  |> aggregateWindow(every: 100ms, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: r._value * 100.0 }))\r\n  |> yield(name: \"brake\")"
    }
   ]
  },
  {
   "title": "Lap Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"f1-telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"f1_telemetry\")\r\n  |> filter(fn: (r) => r._field == \"current_time_ms\")\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / 1000.0 }))\r\n  |> aggregateWindow(every: 500ms, fn: last, createEmpty: false)"
    }
   ]
  }
 ]
}