{
 "title": "Telemery Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Basic telemetry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Stearing Wheel Angle",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"f1-telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"f1_telemetry\")\r\n  |> filter(fn: (r) => r._field == \"steering\")\r\n  |> map(fn: (r) => ({ r with _value: r._value * 180.0 }))\r\n  |> last()"
    }
   ]
  },
  {
   "title": "RPM",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"f1-telemetry\")\r\n  |> range(start: -30s)\r\n  |> filter(fn: (r) => r._measurement == \"f1_telemetry\")\r\n  |> filter(fn: (r) => r._field == \"rpm\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Completed Laps",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"f1-telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"f1_telemetry\")\r\n  |> filter(fn: (r) => r._field == \"completed_laps\")\r\n  |> aggregateWindow(every: 1s, fn: last, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"f1-telemetry\")\r\n  |> range(start: -30s)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"f1_telemetry\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"speed_kmh\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Gear",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 6, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"f1-telemetry\")\r\n  |> range(start: -30s)\r\n  |> filter(fn: (r) => r._measurement == \"f1_telemetry\")\r\n  |> filter(fn: (r) => r._field == \"gear\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Throttle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "targets": [
    {
     "query": "from(bucket: \"f1-telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"f1_telemetry\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"throttle\")\r\n  |> aggregateWindow(every: 100ms, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: r._value * 100.0 }))\r\n  |> yield(name: \"throttle\")"
    }
   ]
  },
  {
   "title": "Brake",
   "type": "timeseries",
   "description": "Brake",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "targets": [
    {
     "query": "from(bucket: \"f1-telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"f1_telemetry\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"brake\")\r\n  |> aggregateWindow(every: 100ms, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: r._value * 100.0 }))\r\n  |> yield(name: \"brake\")"
    }
   ]
  },
  {
   "title": "DRS status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "targets": [
    {
     "query": "from(bucket: \"f1-telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"f1_telemetry\")\r\n  |> filter(fn: (r) => r._field == \"drs\" or r._field == \"drs_enabled\" or r._field == \"drs_available\")\r\n  |> aggregateWindow(every: 500ms, fn: last, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Laps Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "targets": [
    {
     "query": "from(bucket: \"f1-telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"f1_telemetry\")\r\n  |> filter(fn: (r) => r._field == \"current_time_ms\")\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / 1000.0 }))\r\n  |> aggregateWindow(every: 500ms, fn: last, createEmpty: false)\r\n  |> difference(nonNegative: false)\r\n  |> filter(fn: (r) => r._value < 0)\r\n  |> map(fn: (r) => ({ r with _value: -r._value }))"
    }
   ]
  },
  { "title": "Track status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Track Temperature",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"f1-telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"f1_telemetry\")\r\n  |> filter(fn: (r) => r._field == \"road_temp\")\r\n  |> aggregateWindow(every: 5s, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Air Temperature",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"f1-telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"f1_telemetry\")\r\n  |> filter(fn: (r) => r._field == \"air_temp\")\r\n  |> aggregateWindow(every: 5s, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Air Density",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"f1-telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"f1_telemetry\")\r\n  |> filter(fn: (r) => r._field == \"air_density\")\r\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)"
    }
   ]
  },
  { "title": "Tyres", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Front Left (FL)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"f1-telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"f1_telemetry\")\r\n  |> filter(fn: (r) => r._field =~ /tire_temp_fl_(inner|middle|outer)/)\r\n  |> aggregateWindow(every: 500ms, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Front Right (FR)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"f1-telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"f1_telemetry\")\r\n  |> filter(fn: (r) => r._field =~ /tire_temp_fr_(inner|middle|outer)/)\r\n  |> aggregateWindow(every: 500ms, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Rear Left (RL)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"f1-telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"f1_telemetry\")\r\n  |> filter(fn: (r) => r._field =~ /tire_temp_rl_(inner|middle|outer)/)\r\n  |> aggregateWindow(every: 500ms, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Rear Right",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"f1-telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"f1_telemetry\")\r\n  |> filter(fn: (r) => r._field =~ /tire_temp_rr_(inner|middle|outer)/)\r\n  |> aggregateWindow(every: 500ms, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Tire Preassure",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "query": "from(bucket: \"f1-telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"f1_telemetry\")\r\n  |> filter(fn: (r) => r._field =~ /tire_pressure_(fl|fr|rl|rr)/)\r\n  |> aggregateWindow(every: 1s, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Brakes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "panels": [
    {
     "title": "Brakes",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 69 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"f1-telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"f1_telemetry\")\r\n  |> filter(fn: (r) => r._field =~ /brake_temp_(fl|fr|rl|rr)/)\r\n  |> aggregateWindow(every: 500ms, fn: mean, createEmpty: false)"
      }
     ]
    }
   ]
  },
  { "title": "G-Forces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "G-Forces (Lateral, Longitudinal, Vertical)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {
     "query": "from(bucket: \"f1-telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"f1_telemetry\")\r\n  |> filter(fn: (r) => r._field =~ /accg_(lateral|longitudinal|vertical)/)\r\n  |> aggregateWindow(every: 100ms, fn: mean, createEmpty: false)"
    }
   ]
  }
 ]
}